from __future__ import annotations

from typing import List

from .factors import (
    MeanReversion,
    Momentum,
    Volatility,
    DollarVolume,
    Size,
    EarningsYield,
    Profitability,
    DividendYield,
    Beta,
    DownsideBeta,
    AnalystRevision,
    EarningsSurprise,
    Turnover,
    DownsideVol,
    High52wProximity,
    AmihudIlliquidity,
    AmihudIlliquidityLog,
    Coskewness,
    BookToPrice,
    ReturnOnAssets,
    Leverage,
    SalesGrowth,
    AssetGrowth,
    ResidualVol,
    IdiosyncraticVolatility,
    ResidualMomentum,
    CompositeMomentum,
    IndustryCoMomentum,
    VolumeInclusiveICM,
    IndustryCoReversal,
    LogTotalAssets,
    LogEnterpriseValue,
    LogRevenue,
    EfficiencyRatio,
    GrossProfitability,
    SalesGrowthAcceleration,
    NetBuybackYield,
    IndustryMomentum,
    MaxDailyReturn,
    EVToEBITDA,
    InvestmentToAssets,
    PiotroskiFScore,
    AverageTrueRange,
    OnBalanceVolume,
    VWAPDeviation,
    HurstExponent,
    StandardizedUnexpectedEarnings,
    BenfordChiSquareD1,
    BenfordChiSquareD2,
    CashflowYield,
    FreeCashflowYield,
    Accruals,
    RDIntensity,
    NetIssuance,
    ReturnSkewness,
    ReturnKurtosis,
    DividendGrowth,
)


def get_default_factors() -> List:
    """
    Central place to declare the default factor set used by run_factors and demos.
    Modify or extend this list to add/remove factors without changing runner code.
    """
    return [
        Momentum(lookback_days=252, skip_days=21, name="momentum_12m"),
        CompositeMomentum(),
        ResidualMomentum(),
        IndustryCoMomentum(),
        VolumeInclusiveICM(),
        IndustryCoReversal(),
        Volatility(window=60, name="volatility_60d"),
        IdiosyncraticVolatility(window=60),
        DownsideVol(window=60),
        MeanReversion(lookback_days=5, name="mean_reversion_5d"),
        High52wProximity(),
        DollarVolume(window=20, name="dollar_volume_20d"),
        AmihudIlliquidity(window=20),
        AmihudIlliquidityLog(window=20),
        AmihudIlliquidity(window=252, name="amihud_illiq_252d"),
        EfficiencyRatio(window=252),
        ResidualVol(window=252),
        Size(),
        EarningsYield(),
        Profitability(),
        DividendYield(),
        Beta(window=252),
        DownsideBeta(window=252),
        CashflowYield(),
        FreeCashflowYield(),
        GrossProfitability(),
        Accruals(),
        RDIntensity(),
        NetIssuance(),
        NetBuybackYield(),
        InvestmentToAssets(),
        PiotroskiFScore(),
        AverageTrueRange(window=14),
        OnBalanceVolume(),
        VWAPDeviation(window=21),
        HurstExponent(window=252),
        StandardizedUnexpectedEarnings(),
        BenfordChiSquareD1(),
        BenfordChiSquareD2(),
        ReturnSkewness(),
        ReturnKurtosis(),
        DividendGrowth(),
        EVToEBITDA(),
        BookToPrice(),
        ReturnOnAssets(),
        Leverage(),
        SalesGrowth(),
        SalesGrowthAcceleration(),
        AssetGrowth(),
        AnalystRevision(),
        EarningsSurprise(),
        Turnover(),
        Coskewness(window=252),
        IndustryMomentum(),
        MaxDailyReturn(window=21, name="max_daily_return_1m"),
        LogTotalAssets(),
        LogEnterpriseValue(),
        LogRevenue(),
    ]
